### ISSUE TITLE
[Mobile] [Player Page] Stats don't fit on mobile device screen, but scrolling on the stats page drags the bar out to the side to block the view

### ISSUE THREAD

**Issue by nilleahcim** [blert-io/blert#31]
https://github.com/blert-io/blert/assets/68204294/ae530607-0103-4f6e-a700-f4136bc0c65f

**Comment by nilleahcim** [comment]
I think the side bar should only come out when you drag from the side, not from anywhere on the screen

**Comment by nilleahcim** [comment]
After discussion with Alexei, we're finding that it is only an issue with opening blert.io through discord mobile app.

**Comment by jowdancing** [comment]
https://github.com/blert-io/blert/assets/25463845/65725826-926f-40ba-81a2-e810a4930e72
https://github.com/blert-io/blert/assets/25463845/c37ba82e-7b06-4d97-a2f9-4a450bfbcb92

It doesn't seem to be where you open it from but the length of the username. Attached videos are from Safari and Firefox.
