### ISSUE TITLE
Blert doesn't recognize voidwaker specs, and voidwaker spec doesn't have a unique name  "attacked"

### ISSUE THREAD

**Issue by wizzyhatg** [blert-io/blert#38]
https://www.blert.io/raids/tob/c17ac5ae-9a5b-4037-9fd7-88a19fe31dae/overview I voidwaker specced on Maiden, Bloat, and Verzik, did not voidwaker scratch. Raid review shows generic "attacked" instead of voidwakered, and does not show spec orb. I tried to fix it but couldn't figure out where the attack name definitions were coming from, sorry.

**Comment by frolv** [comment]
Voidwaker isn't tracked by the plugin currently, so it just falls back to a generic attack. I'll go through and add some missing weapons before the first release of the plugin, and will include voidwaker as part of that.
